import 'package:logger/logger.dart';

/* https://shop.pallavinamdev.com/PHP_CollApp/  */
const baseurl = 'http://shop.pallavinamdev.com/PHP_Demo/';
const loginurl = 'p_user_login.php';
const datakey = 'R9WM1wN2ZDM5zZw+NQ==';
const goldrateurl = 'p_user_getGoldRate.php';
const schemedetailurl = 'p_user_schemeDetail.php';
const userschemesurl = 'p_user_cusSchemes.php';
const contactusurl = 'p_user_getCustomerSupport.php';
const akshayanidhihystory = 'p_user_akshayaNidhiLedger.php';
const goldplushystory = 'p_user_goldPlusLedger.php';
const sendotpurl = 'p_user_OTPGeneration.php';
const verifyotpurl = 'p_user_OTPVerification.php';
const relationshipurl = 'p_user_SelRelationship.php';
const documenttypeurl = 'p_user_SeltDocumentType.php';
const getbranchesurl = 'p_user_SelBranch.php';
const updatepaymentstatusurl = "p_user_insPayment.php";
const getsalesmanurl = 'p_user_SelBranchEmployees.php';
const getbranchschemesurl = 'p_user_SelBranchSchemes.php';
const schemetenureurl = 'p_user_SelTenure.php';
const createnewuserurl = 'p_user_InsSchemeNewCustomer.php';
const uploadimageurl = 'p_user_uploadImage.php';
const resetpinurl = 'p_user_updatePin.php';
const resetpinotpurl = 'p_user_insOTP.php';
const resetpinotpverifyurl = 'p_user_verifyOTP.php';
const paymenthystoryurl = 'p_user_insPaymentHistory.php';
const paymentcallbackurl = 'p_payment_callback.php';
const userschemehomeurl = 'p_user_InsSchemeExistingCustomer.php';
var logger = Logger();
